### PR TITLE
Adds minor tweaks to links.

### PR DESCRIPTION
**Pull request by sleslie23**
We had to change the URL in the doc update. Sorry for the extra PR!

### CODE REVIEW

**Comment by sleslie23** [comment]
Also, next PR I'll fix the line lengths!

**Comment by jncd** [comment]
haha you noticed!
Yes, you know I have a thing about long lines.

**Comment by ljarzynski** [comment]
BLT says Hi! @sleslie23 Thanks!

**Comment by sleslie23** [comment]
Thanks @ljarzynski !!!! See you Friday?

**Comment by ljarzynski** [comment]
I think so ;)

**Pull request merged**
