### PR TITLE
Adds content and images changes.

### PR DESCRIPTION
**Pull request by sleslie23**
Hello PCF doc team!

I've never created a PR from outside Pivotal, so let me know if there are any problems. I saved a copy of my content locally just in case!

I added content to a branch called 1.5.1. This will eventually be merged into master, but we aren't sure exactly when the Mule tile will release. I wanted to get the major changes to you now. Any additional changes will be much smaller PRs.

The subnav PR will be along shortly!

Thanks in advance! Hope all is well!

### CODE REVIEW

**Comment by pspinrad** [comment]
Thanks, bud! ( @sleslie23 )

**Comment by sleslie23** [comment]
Thanks @pspinrad !!!

**Comment by jncd** [comment]
Hi @sleslie23 Have you done the PR for the subnav already? (To add the new configuring page?)
We're having some concourse trouble today, so you might not see your update on the staging site yet. Thanks, Jane

**Comment by sleslie23** [comment]
Hi Jane! Not yet, but I'll submit it when I get to the office. It's ok if
the docs don't appear on the staging yet. I don't think our tile will be
ready until early next week.

Thanks!

**Comment by mohanpindyala** [comment]
Images are not zoomable when viewed from browser , is there a way to show images bigger when I click on them ?

**Comment by sleslie23** [comment]
@mohanpindyala Hey Mohan! The Mulesoft docs wrap images in a <div> that is defined to display the images in a larger window. I don't think there is a way to do that in the Pivotal docs.

**Comment by sleslie23** [comment]
See also: https://github.com/pivotal-cf/docs-book-partners/pull/2

**Pull request merged**
