### PR TITLE
Update index.html.md.erb

### PR DESCRIPTION
**Pull request by sleslie23**
Clarifying supported versions since we are not currently testing on 1.9.

### CODE REVIEW

**Comment by bentarnoff** [comment]
Hey @sleslie23 thanks for your request. Unfortunately our internal tooling has informed us that you are a suspicious character who may have malicious intent. Would you be willing to answer a few questions to confirm the quality of your character?

**Comment by sleslie23** [comment]
My character is pristine. Do what you must.

**Comment by ljarzynski** [comment]
@sleslie23 You may consider submitting PRs in person. Just a quick walk over.

**Comment by sleslie23** [comment]
@bentarnoff @ljarzynski will vouch for me.

**Comment by sleslie23** [comment]
@animatedmax Where's my "Thanks @sleslie23?"

**Comment by bentarnoff** [comment]
Thanks @sleslie23 !!!

**Comment by animatedmax** [comment]
@sleslie23 I wanted to make sure we merged the PR, but I didn't want to stop the fun bantering!

Thanks, @sleslie23 !

**Comment by sleslie23** [comment]
@animatedmax Oh, that doesn't have to stop! When are we having lunch? I have, not one, but two presents for you.

**Pull request merged**
